# your override should supply an envName
envName: null
useEnvNameForApp: false

# if set, override all Applications to use this project
# projectOverride: default


default:
  project:
    roles: |
      - name: read-only
        description: Read-only privileges within project
        policies:
        - p, proj:{{ $.curProjName }}:read-only, applications, get, {{ $.curProjName }}/*, allow
      - name: ci-role
        description: Role to allow CICD pipeline to sync apps within project
        policies:
        - p, proj:{{ $.curProjName }}:ci-role, applications, sync, {{ $.curProjName }}/*, allow
    destinations: |
      - namespace: {{ $.Values.default.app.destination.namespace | required "Missing proj dest namespace"}}
        server: {{ $.Values.default.app.destination.server | required "Missing proj dest server" }}
  app:
    enableAutoSync: null
    autoSyncPrune: true
    destination:
      namespace: null
      server: https://kubernetes.default.svc
    project: default
    source:
      path: null
      repoURL: null
      targetRevision: HEAD

      # extraSourceFields: |
      #   helm:
      #     valueFiles:
      #     - {{ $.Values.envName }}-values.yaml

      #  kustomize:
      #    namePrefix: prod-
    #extraFields: |
    #  Default fields you want on all applications, unless the app individually overrides

projects:

  # hsd-um:
  #   description: 'HSD User Management'
  #   sourceRepos:
  #   #- https://MY_APPS_REPOSITORY/auth/*
  #   - "*"


applications:
  guest-book:
    enabled: true
    destination:
      namespace: argocd
      server: null
    project: default
    source:
      path: .
      repoURL: https://github.com/soubhagya-pradhan/guest-book-test
      targetRevision: HEAD
      helm:
      valueFiles:
        - values.yaml

  hello-world:
    enabled: true
    destination:
      namespace: argocd
      server: null
    project: default
    source:
      path: charts/hello-world
      repoURL: https://github.com/soubhagya-pradhan/helm-hello-world
      targetRevision: HEAD
      helm:
      valueFiles:
        - values.yaml

  
